export const SET_TOKEN = 'SET_TOKEN'
export const SET_LOADING = 'SET_LOADING'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_ERROR = 'SET_ERROR'
export const SET_USER = 'SET_USER'
export const SET_OWNER = 'SET_OWNER'
export const LOGOUT = 'LOGOUT'